name: Run Paraphraser
on: [push, pull_request]

jobs:
  run-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          pip install transformers sentencepiece  # Required for Pegasus/T5

      - name: Run model
        run: |
          python main.py
